// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvqvbyrhpbdrbymhthup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cXZieXJocGJkcmJ5bWh0aHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMDkwNzUsImV4cCI6MjA1ODc4NTA3NX0.4_ORyxpCSIP2J5U95yZfIo7YDAxnBq4j1O0UDlzjtC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);